print ("Gbemi")
print("I'm going to create a list")
lottery=[5,15,10,20]
print(lottery)
print("I have created the list")
print("I am going to add the number 1 to the list")
lottery.append(1)
print(lottery)
print("I'm going to find out the lenght of the list")
lenght=len(lottery)
print("the lenght of the list is "+ str(lenght))
print("I am going to sort the list now")
lottery.sort()
print (lottery)
print("Deleting a number in the list,you need to use index ")
print("I'm deleting the number value at index 2")
del lottery[2]
print("I'd like to reverse my list now")
lottery.reverse()
print (lottery)